{
  "name": "GataBot-MD",
  "version": "1.7.0",
  "description": "Super Bot WhatsApp",
  "main": "index.js",
  "type": "module",
  "directories": {
    "lib": "lib",
    "src": "src",
    "plugins": "plugins"
  },
  "scripts": {
    "start": "node index.js",
    "qr": "node index.js qr",
    "code": "node index.js code",
    "test": "node test.js",
    "test2": "nodemon index.js"
  },
  "homepage": "https://github.com/GataNina-Li/GataBot-MD",
  "author": {
    "name": "GataNina-Li"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/GataNina-Li/GataBot-MD.git"
  },
  "bugs": {
    "url": "https://github.com/GataNina-Li/GataBot-MD/issues"
  },
  "license": "GPL-3.0-or-later",
  "dependencies": {
    "@whiskeysockets/baileys": "github:EdderBot02/bail",
    "@bochilteam/scraper": "^5.0.1",
    "@brandond/findthelyrics": "^2.0.5",
    "@green-code/music-track-data": "^2.0.3",
    "@shineiichijo/marika": "^2.0.6",
    "@vitalets/google-translate-api": "^8.0.0",
    "acrcloud": "^1.4.0",
    "api-dylux": "^1.8.3",
    "express": "^4.18.1",
    "aptoide-scraper": "^1.0.1",
    "@seald-io/nedb": "^4.1.1",
    "archiver": "^7.0.1",
    "awesome-phonenumber": "^3.4.0",
    "axios": "^1.9.0",
    "p-queue": "^8.1.0",
    "cfonts": "^3.3.0",
    "chalk": "^5.4.1",
    "cheerio": "1.0.0-rc.12",
    "countries-and-timezones": "3.6.0",
    "express": "^4.17.3",
    "file-type": "^17.1.1",
    "fluent-ffmpeg": "^2.1.2",
    "formdata-node": "^4.3.2",
    "google-libphonenumber": "3.2.38",
    "hispamemes": "^1.0.7",
    "human-readable": "^0.2.1",
    "jsdom": "^20.0.1",
    "lodash": "^4.17.21",
    "lowdb": "^3.0.0",
    "libphonenumber-js": "^1.10.55",
    "megajs": "^1.2.2",
    "module-gatadios": "^1.0.9",
    "moment-timezone": "^0.5.34",
    "mongoose": "^6.3.3",
    "node-fetch": "^3.2.0",
    "node-cache": "^5.1.2",
    "node-gtts": "^2.0.2",
    "node-webpmux": "^3.1.1",
    "node-os-utils": "^1.3.6",
    "openai": "^3.3.0",
    "pino": "^7.8.0",
    "performance-now": "^2.1.0",
    "qrcode": "^1.5.0",
    "similarity": "^1.2.1",
    "socket.io": "^4.4.1",
    "fuzzysort": "^1.0.0",
    "syntax-error": "^1.4.0",
    "terminal-image": "^2.0.0",
    "url-regex-safe": "^3.0.0",
    "javascript-obfuscator": "^4.0.0",
    "wa-sticker-formatter": "^4.3.2",
    "yargs": "^17.3.1",
    "yt-search": "^2.10.3",
    "google-it": "^1.6.3",
    "@hiudyy/ytdl": "^0.2.3",
    "ytdl-core": "latest"
  },
  "devDependencies": {
    "eslint": "^8.45.0",
    "eslint-config-google": "^0.14.0",
    "prettier": "^3.6.2"
  }
}
