[
{"motivasi":"Betapapun sulitnya hidup, selalu ada sesuatu yang dapat kamu lakukan dan berhasil. - Stephen Hawking"},
{"motivasi":"Hidup bukan tentang menemukan dirimu sendiri. Hidup adalah bagaimana membangun dirimu. - George Bernard Shaw"},
{"motivasi":"Cintai hidup yang Anda jalani. Jalani hidup yang Anda cintai. - Bob Marley"},
{"motivasi":"Orang pesimis melihat kesulitan di setiap kesempatan. Orang yang optimis melihat peluang dalam setiap kesulitan. -Winston Churchill"},
{"motivasi":"Jangan khawatir tentang kegagalan, khawatirkan tentang peluang yang kamu lewatkan ketika kamu bahkan tidak mencoba.- Jack Canfield"},
{"motivasi":"Tidak ada rahasia sukses. Itu adalah hasil dari persiapan, kerja keras, dan belajar dari kegagalan. - Colin Powell"},
{"motivasi":"Orang sukses melakukan apa yang orang tidak sukses tidak mau lakukan. Jangan berharap itu lebih mudah; berharaplah Anda lebih baik.- Jim Rohn"},
{"motivasi":"Dalam hidup ini kita tidak bisa melakukan hal-hal besar. Kita hanya bisa melakukan hal-hal kecil dengan cinta yang besar. - Bunda Teresa"},
{"motivasi":"Menang bukanlah segalanya, tetapi keinginan untuk menang adalah segalanya. - Vince Lombardi"},
{"motivasi":"Tiga hal penting dalam hidup: kesehatanmu, misimu, dan orang yang kamu cintai. - Naval Ravikant"},
{"motivasi":"Jangan takut hidup. Percayalah bahwa hidup itu layak dijalani dan keyakinan Anda akan membantu menciptakan fakta.- William James"},
{"motivasi":"Saat kita berusaha untuk menjadi lebih baik dari kita, segala sesuatu di sekitar kita juga menjadi lebih baik. - Paulo Coelho"},
{"motivasi":"Kesuksesan dan kegagalan adalah sama-sama bagian dalam hidup. Keduanya hanya sementara.- Shah Rukh Khan"},
{"motivasi":"Hitunglah umurmu dengan teman, bukan tahun. Hitunglah hidupmu dengan senyum, bukan air mata.- John Lennon"},
{"motivasi":"Semua kehidupan adalah eksperimen. Makin banyak eksperimen yang kamu buat, makin baik. - Ralph Waldo Emerson"},
{"motivasi":"Satu-satunya perjalanan yang mustahil adalah perjalanan yang tidak pernah Anda mulai. - Tony Robbins"},
{"motivasi":"Sukses bukanlah akhir; kegagalan tidak fatal: Yang terpenting adalah keberanian untuk melanjutkan. - Winston S. Churchill"},
{"motivasi":"Banyak dari kegagalan hidup adalah orang-orang yang tidak menyadari betapa dekatnya mereka dengan kesuksesan ketika mereka menyerah.- Thomas A. Edison"},
{"motivasi":"Kamu punya otak di kepalamu. Kamu punya kaki di sepatumu. Kamu bisa mengarahkan dirimu sendiri ke arah mana pun yang kamu pilih. - Dr. Seuss"},
{"motivasi":"Jalan menuju sukses dan jalan menuju kegagalan hampir persis sama.- Colin R. Davis"},
{"motivasi":"Sebarkan cinta ke mana pun kamu pergi. Jangan biarkan orang lain mendatangimu tanpa pergi dengan lebih bahagia.- Bunda Teresa"},
{"motivasi":"Ketika kamu mencapai ujung tali, ikat simpul di dalamnya dan bertahanlah.- Franklin D. Roosevelt"},
{"motivasi":"Kebahagiaan adalah ketika apa yang Anda pikirkan, apa yang Anda katakan, dan apa yang Anda lakukan selaras. - Mahatma Gandhi"},
{"motivasi":"Jangan menilai setiap hari dengan panen yang kamu tuai, tetapi dengan benih yang kamu tanam. - Robert Louis Stevenson"},
{"motivasi":"Masa depan adalah milik mereka yang percaya pada keindahan impian mereka. - Eleanor Roosevelt"},
{"motivasi":"Hidup adalah petualangan yang berani atau tidak sama sekali. - Helen Keller"},
{"motivasi":"Cara untuk memulai adalah dengan berhenti berbicara dan mulai melakukan.- Walt Disney"},
{"motivasi":"Waktumu terbatas, jadi jangan sia-siakan dengan menjalani hidup orang lain. Jangan terjebak oleh hidup dengan hasil pemikiran orang lain. - Steve Jobs"},
{"motivasi":"Jika kehidupan dapat diprediksi, maka kehidupan akan berhenti, dan tanpa rasa. - Eleanor Roosevelt"},
{"motivasi":"Jika kamu menetapkan tujuan sangat tinggi dan kamu gagal, maka kamu akan gagal di atas kesuksesan orang lain. - James Cameron"},
{"motivasi":"Katakan kepadaku dan aku lupa. Ajari aku dan aku ingat. Libatkan aku dan aku belajar. - Benjamin Franklin"},
{"motivasi":"Hal-hal terbaik dan terindah di dunia tidak dapat dilihat atau bahkan disentuh - semuanya harus dirasakan dengan hati. - Helen Keller"},
{"motivasi":"Pada saat-saat merasakan kegelapan, kita harus fokus untuk melihat cahaya. - Aristoteles"},
{"motivasi":"Siapa pun yang bahagia akan membuat orang lain juga bahagia.- Anne Frank"},
{"motivasi":"Kamu akan menghadapi banyak kekalahan dalam hidup, tapi jangan pernah membiarkan dirimu dikalahkan.- Maya Angelou"},
{"motivasi":"Tujuan hidup kita adalah menjadi bahagia.- Dalai Lama"}
]
