import fetch from 'node-fetch'
let handler = async (m, { conn, text, command, usedPrefix }) => {
if (!db.data.chats[m.chat].modohorny && m.isGroup) throw `${lenguajeGB['smsContAdult']()}`
await delay(5000)
let frep = { contextInfo: { externalAdReply: {title: wm, body: lenguajeGB.smsCont18Porn2(), sourceUrl: redesMenu.getRandom(), thumbnail: await(await fetch(img16)).buffer() }}}
let user = global.db.data.users[m.sender]
let yh = global.darling
let url = yh[Math.floor(Math.random() * yh.length)]
await conn.sendButton(m.chat, lenguajeGB.smsCont18Porn(), ` *_${lenguajeGB['smsBotonM7']()}_* » ${user.premiumTime > 0 ? '✅' : '❌'}\n` + wm, url, [[lenguajeGB.smsSig(), `${usedPrefix + command}`]], m, frep)
}
handler.command = /^(darling)$/i
handler.level = 5
handler.money = 125
export default handler
const delay = time => new Promise(res => setTimeout(res, time))
  
global.darling = ['https://img.nickpic.host/q7SLrX.jpg',
'https://img.nickpic.host/q7STNf.jpg',
'https://img.nickpic.host/q7Skee.jpg',
'https://img.nickpic.host/q7SeMF.jpg',
'https://img.nickpic.host/q7S9lM.jpg',
'https://img.nickpic.host/q7S0WP.jpg',
'https://img.nickpic.host/q7Sfz5.jpg',
'https://img.nickpic.host/q7SVuD.jpg',
'https://img.nickpic.host/q7SNmd.jpg',
'https://img.nickpic.host/q7SYNq.jpg',
'https://img.nickpic.host/q7SPQb.jpg',
'https://img.nickpic.host/q7SZo6.jpg',
'https://img.nickpic.host/q7SdAp.jpg',
'https://img.nickpic.host/q7SyzY.jpg',
'https://img.nickpic.host/q7cGZA.jpg',
'https://img.nickpic.host/q7cm5G.jpg',
'https://img.nickpic.host/q7coMz.jpg',
'https://img.nickpic.host/q7cxrW.jpg',
'https://img.nickpic.host/q7cpkc.jpg',
'https://img.nickpic.host/q7cBQ1.jpg',
'https://img.nickpic.host/q7cbVj.jpg',
'https://img.nickpic.host/q7csoJ.jpg',
'https://img.nickpic.host/q7c3An.jpg',
'https://img.nickpic.host/q7cF7s.jpg',
'https://img.nickpic.host/q7caZ2.jpg',
'https://img.nickpic.host/q7cl5Q.jpg',
'https://img.nickpic.host/q7c5Rx.jpg',
'https://img.nickpic.host/q7cSkN.jpg',
'https://img.nickpic.host/q7cgsO.jpg',
'https://img.nickpic.host/q7cqUm.jpg',
'https://img.nickpic.host/q7cuV8.jpg',
'https://img.nickpic.host/q7cEpq.jpg',
'https://img.nickpic.host/q7ch7D.jpg',
'https://img.nickpic.host/q7cOAd.jpg',
'https://img.nickpic.host/q7c6d5.jpg',
'https://img.nickpic.host/q7cQ5P.jpg',
'https://img.nickpic.host/q7cURM.jpg',
'https://img.nickpic.host/q7cXJF.jpg',
'https://img.nickpic.host/q7cnse.jpg',
'https://img.nickpic.host/q7ctUX.jpg',
'https://img.nickpic.host/q7cMfb.jpg',
'https://img.nickpic.host/q7c1pf.jpg',
'https://img.nickpic.host/q7c4E6.jpg',
'https://img.nickpic.host/q7cD8p.jpg',
'https://img.nickpic.host/q7cwdY.jpg',
'https://img.nickpic.host/q7c7SA.jpg',
'https://img.nickpic.host/q7c81G.jpg',
'https://img.nickpic.host/q7cH3c.jpg',
'https://img.nickpic.host/q7cKJz.jpg',
'https://img.nickpic.host/q7cNUW.jpg',
'https://img.nickpic.host/q7cVf1.jpg',
'https://img.nickpic.host/q7c2EJ.jpg',
'https://img.nickpic.host/q7c0vj.jpg',
'https://img.nickpic.host/q7c98n.jpg',
'https://img.nickpic.host/q7ceys.jpg',
'https://img.nickpic.host/q7cL1Q.jpg',
'https://img.nickpic.host/q7cJS2.jpg',
'https://img.nickpic.host/q7cPLx.jpg',
'https://img.nickpic.host/q7cW3N.jpg',
'https://img.nickpic.host/q7cZXO.jpg',
'https://img.nickpic.host/q7gGv8.jpg',
'https://img.nickpic.host/q7cd0m.jpg',
'https://img.nickpic.host/q7gIOq.jpg',
'https://img.nickpic.host/q7goyD.jpg',
'https://img.nickpic.host/q7gm8d.jpg',
'https://img.nickpic.host/q7gvc5.jpg',
'https://img.nickpic.host/q7gx1P.jpg',
'https://img.nickpic.host/q7grFF.jpg',
'https://img.nickpic.host/q7gBLM.jpg',
'https://img.nickpic.host/q7gsXe.jpg',
'https://img.nickpic.host/q7g30X.jpg',
'https://img.nickpic.host/q7gaxb.jpg',
'https://img.nickpic.host/q7gjOf.jpg',
'https://img.nickpic.host/q7glK6.jpg',
'https://img.nickpic.host/q7gSGp.jpg',
'https://img.nickpic.host/q7gccY.jpg',
'https://img.nickpic.host/q7gg4A.jpg',
'https://img.nickpic.host/q7gqPG.jpg',
'https://img.nickpic.host/q7gEic.jpg',
'https://img.nickpic.host/q7gAFz.jpg',
'https://img.nickpic.host/q7gO0W.jpg',
'https://img.nickpic.host/q7gChj.jpg',
'https://img.nickpic.host/q7gQKJ.jpg',
'https://img.nickpic.host/q7g6x1.jpg',
'https://img.nickpic.host/q7gXGn.jpg',
'https://img.nickpic.host/q7gigs.jpg',
'https://img.nickpic.host/q7gn42.jpg',
'https://img.nickpic.host/q7gtPQ.jpg',
'https://img.nickpic.host/q7g1iN.jpg',
'https://img.nickpic.host/q7gRax.jpg',
'https://img.nickpic.host/q7g42O.jpg',
'https://img.nickpic.host/q7gwBm.jpg',
'https://img.nickpic.host/q7g7Yq.jpg',
'https://img.nickpic.host/q7gzh8.jpg',
'https://img.nickpic.host/q7gKGd.jpg',
'https://img.nickpic.host/q7gYgD.jpg',
'https://img.nickpic.host/q7gHD5.jpg',
'https://img.nickpic.host/q7gfaM.jpg',
'https://img.nickpic.host/q7gNPP.jpg',
'https://img.nickpic.host/q7g0nF.jpg',
'https://img.nickpic.host/q7g22e.jpg',
'https://img.nickpic.host/q7geBX.jpg',
'https://img.nickpic.host/q7gPI6.jpg',
'https://img.nickpic.host/q7gk6b.jpg',
'https://img.nickpic.host/q7gJYf.jpg',
'https://img.nickpic.host/q7gTqp.jpg',
'https://img.nickpic.host/q7gWDY.jpg',
'https://img.nickpic.host/q7gZTA.jpg',
'https://img.nickpic.host/q7qGnz.jpg',
'https://img.nickpic.host/q7gyjG.jpg',
'https://img.nickpic.host/q7qI9c.jpg',
'https://img.nickpic.host/q7qoBW.jpg',
'https://img.nickpic.host/q7qp61.jpg',
'https://img.nickpic.host/q7qBIJ.jpg',
'https://img.nickpic.host/q7qvHj.jpg',
'https://img.nickpic.host/q7qbqn.jpg',
'https://img.nickpic.host/q7qrws.jpg',
'https://img.nickpic.host/q7qFjQ.jpg',
'https://img.nickpic.host/q7qsT2.jpg',
'https://img.nickpic.host/q7qatx.jpg',
'https://img.nickpic.host/q7qj9N.jpg',
'https://img.nickpic.host/q7qcH8.jpg',
'https://img.nickpic.host/q7q5bO.jpg',
'https://img.nickpic.host/q7qSCm.jpg',
'https://img.nickpic.host/q7qqmq.jpg']
