const contoh = `*Asmaul Husna*
`
// data here
const anjuran = `
Desde Abu Hurairah radhiallahu anhu, Rasulullah SAW dijo: "Tengo noventa y nueve nombres, cien menos 1. Quien los memorice entrará en el Paraíso, y él es un acorde que ama el acorde."
Significado: "De hecho, yo tengo noventa y nueve nombres, también conocido como cien menos uno. Quien los cuente, entrará en el cielo; Él es Witr y ama a Witr".`

let handler = async (m, { args, usedPrefix, command }) => {
    let json = JSON.parse(JSON.stringify(global.asmaulhusna))
    let data = json.map((v, i) => `${i + 1}. ${v.latin}\n${v.arabic}\n${v.translation_id}`).join('\n\n')
    if (isNaN(args[0])) throw `Ejemplo:\n${usedPrefix + command} 1`
    if (args[0]) {
        if (args[0] < 1 || args[0] > 99) throw `mínimo 1 y máximo 99!`
        let { index, latin, arabic, translation_id, translation_en } = json.find(v => v.index == args[0].replace(/[^0-9]/g, ''))
        return m.reply(`🔢 *Número:* ${index}
${arabic}

${latin}

${translation_id}

${translation_en}
`.trim())
    }
    m.reply(contoh + data + anjuran)
}
handler.help = ['frase [escribe un número 1 - 99]']
handler.tags = ['quran']
handler.command = /^(frase(s)?)$/i
export default handler

global.asmaulhusna = [
    {
        index: 1,
        latin: "💐 *Autor:* *John Maxwell*",
        arabic: "💐 *Frase:* _En la vida algunas veces se gana, otras veces se aprende._",
        translation_id: "💐 *Opinión:* Hay que aprender de esos momentos desagradables, para de esta manera seguir creciendo como individuos. En otras palabras, no importa cómo caes, sino cómo te levantas.",
        translation_en: "En otras palabras, no importa cómo caes, sino cómo te levantas."
    },
    {
        index: 2,
        latin: "💐 *Autor:* *Paulo Coelho*",
        arabic: "💐 *Frase:* _No midas tu riqueza por el dinero que tienes, mídela por aquellas cosas que tienes y que no cambiarías por dinero._",
        translation_id: "💐 *Opinión:* En una sociedad materialista es fácil autoevaluarse en función de las posesiones que tenemos, y este tipo de valoraciones son muy negativas para la autoestima.",
        translation_en: "Además, lo que realmente te hará feliz en el día a día, son esas pequeñas cosas y esos momentos agradables."
    },
    {
        index: 3,
        latin: "💐 *Autor:* *Anónimo*",
        arabic: "💐 *Frase:* _Pedir perdón es de inteligentes, perdonar es de nobles y perdonarse es de sabios._",
        translation_id: "💐 *Opinión:* El perdón es una de las mejores terapias emocionales. Si pides perdón y si perdonas, demuestra tu grandeza como individuo. Pero más grande eres, y mejor vas a estar emocionalmente, si también te perdonas a ti mismo. Algo que parece fácil en la teoría, pero que se vuelve complicado en la práctica.",
        translation_en: "Si te identificas con esta frase porque te cuesta perdonarte a ti mismo, el Mindfulness te puede ser de gran utilidad. También existe una filosofía hawaiana llamada Ho'oponopono que basa su efectividad en el perdón espiritual."
    },
    {
        index: 4,
        latin: "💐 *Autor:* *Anónimo*",
        arabic: "💐 *Frase:* _Si quieres algo que nunca tuviste, debes hacer algo que nunca hiciste._",
        translation_id: "💐 *Opinión:* Si haces siempre lo mismo, seguramente siempre tendrás las mismas consecuencias. ",
        translation_en: "Si lo que quieres es tener nuevas experiencias, conocer a gente interesante o crecer en el trabajo, mejor que empieces a plantearte nuevas actividades y hagas cosas que habitualmente no haces."
    },
    {
        index: 5,
        latin: "💐 *Autor:* *Proverbio turco*",
        arabic: "💐 *Frase:* _El que busca un amigo sin defectos se queda sin amigos._",
        translation_id: "💐 *Opinión:* La intención esta frase es hacernos notar que todos tenemos defectos y cometemos muchos errores, no hay persona perfecta en este mundo. ",
        translation_en: "Ser una persona demasiado perfeccionista provoca consecuencias negativas para uno mismo."
    },
    {
        index: 6,
        latin: "💐 *Autor:* *Proverbio escocés*",
        arabic: "💐 *Frase:* _La sonrisa cuesta menos que la electricidad y da más luz._",
        translation_id: "💐 *Opinión:* Esta frase es una de esas frases inspiradoras, pero también es una frase sabia. Sonreír ayuda a mantener el buen humor, embellece el rostro y despierta buenos pensamientos.  ",
        translation_en: "No es lo mismo pedirle algo a alguien fríamente, que pedirlo con una sonrisa, pues la sonrisa no solamente produce un efecto muy positivo en nosotros mismos, también en la otra persona."
    },
    {
        index: 7,
        latin: "💐 *Autor:* *Henry Ford*",
        arabic: "💐 *Frase:* _No encuentres la falta, encuentra el remedio._",
        translation_id: "💐 *Opinión:* Esta frase me recuerda a una que un buen amigo siempre me decía: “ Si no formas parte de la solución, pasas a formar parte del problema.",
        translation_en: "Ambas frases no nos quieren decir que no debemos buscar el origen del problema, pues es necesario hacerlo. Pero en lugar de quedarnos lamentando la falla de manera eterna, debemos solucionar lo antes posible lo que ha ocurrido mal. Esta es la clave para mejorar.",
    },
    {
        index: 8,
        latin: "💐 *Autor:* *William George Ward*",
        arabic: "💐 *Frase:* _El pesimista se queja del viento; el optimista espera que cambie; el realista ajusta las velas._",
        translation_id: "💐 *Opinión:* Tanto ser un pesimista como demasiado optimista puede traer consecuencias negativas para uno mismo.",
        translation_en: "El pesimista todo lo va a ver mal y no existirá nada para que ese mal cambie. El optimista todo lo va a ver bien y distorsiona la realidad para que encaje con sus pensamientos. En cambio, una persona realista trata de solucionar los problemas pese a saber que es complicado en muchas ocasiones. Es decir, mantiene los pies en el suelo y actúa de manera sensata.",
    },
    {
        index: 9,
        latin: "💐 *Autor:* *Madre Teresa de Calcuta*",
        arabic: "💐 *Frase:* _A veces sentimos que lo que hacemos es tan solo una gota en el mar, pero el mar sería mucho menos si le faltara una gota._",
        translation_id: "💐 *Opinión:* Significa que aunque sintamos que lo que hacemos no sirve para nada, cada cosa que hacemos tiene una consecuencia.",
        translation_en: "A veces no somos capaces de ver esa consecuencia inmediatamente, o a veces es solamente un paso más en un camino que estamos recorriendo. Se trata de ir construyendo y al final llegará la recompensa.",
    },
    {
        index: 10,
        latin: "💐 *Autor:* *Buddha*",
        arabic: "💐 *Frase:* _La reflexión es el camino hacia la inmortalidad; la falta de reflexión, el camino hacia la muerte._",
        translation_id: "💐 *Opinión:* Esta frase extraída de la filosofía budista hace referencia a la importancia de la reflexión en el desarrollo personal y en el aprendizaje por y para la vida.",
        translation_en: "Todos hemos aprendido de los errores, pero cada uno vive las experiencias de manera única. Para poder retener estas experiencias, es necesario un proceso de pensamiento activo sobre lo que vivimos, para, de esta manera, cuestionarnos el sentido que tienen estas experiencias para nosotros.",
    },
    {
        index: 11,
        latin: "💐 *Autor:* *Francis Bacon*",
        arabic: "💐 *Frase:* _La ocasión hay que crearla, no esperar a que llegue._",
        translation_id: "💐 *Opinión:* Esta frase se refiere a que las oportunidades hay que buscarlas, no van a venir solas.",
        translation_en: "Es decir, si queremos algo, hay que luchar por ello. Un antídoto contra la Parálisis del análisis.",
    },
    {
        index: 12,
        latin: "💐 *Autor:* *Napoleón*",
        arabic: "💐 *Frase:* _Los sabios son los que buscan la sabiduría; los necios piensan haberla encontrado._",
        translation_id: "💐 *Opinión:* Esta frase se refiere a que las oportunidades hay que buscarlas, no van a venir solas.",
        translation_en: "Es decir, si queremos algo, hay que luchar por ello. Un antídoto contra la Parálisis del análisis.",
    },
    {
        index: 13,
        latin: "💐 *Autor:* *Séneca*",
        arabic: "💐 *Frase:* _No es pobre el que tiene poco, sino el que mucho desea._",
        translation_id: "💐 *Opinión:* Esta frase es igual a la frase “No es más rico el que más tiene, sino el que menos necesita”, y se refiere a que las personas que menos cosas materiales desean o necesitan, son las que definitivamente van a ser más felices en la vida.",
        translation_en: "Tener mucho no significa ser más feliz, pues si uno se contenta con poco, no necesita tener mucha riqueza.",
    },
    {
        index: 14,
        latin: "💐 *Autor:* *William Shakespeare*",
        arabic: "💐 *Frase:* _Si no recuerdas la más ligera locura en que el amor te hizo caer, no has amado._",
        translation_id: "💐 *Opinión:* Esta frase del autor de Romeo y Julieta nos recuerda que el enamoramiento es una de las sensaciones más extraordinarias de las que puede disfrutar el ser humano.",
        translation_en: "El amor es como una droga que te puede hacer sentir en pleno subidón y te puede hacer cometer locuras increíbles que jamás hayas pensado.",
    },
    {
        index: 15,
        latin: "💐 *Autor:* *Anónimo*",
        arabic: "💐 *Frase:* _Cuando el sabio señala la luna, el tonto se fija en el dedo._",
        translation_id: "💐 *Opinión:* Los necios no quieren ver más allá de lo que sus ojos pueden ver.",
        translation_en: "En cambio, los sabios expanden su mente, son creativos y reflexionan. Mientras el sabio es un explorador, el necio es conformista.",
    },
    {
        index: 16,
        latin: "💐 *Autor:* *Ralph Waldo Emerson*",
        arabic: "💐 *Frase:* _Un amigo es una persona con la que se puede pensar en voz alta._",
        translation_id: "💐 *Opinión:* Un auténtico amigo es esa persona que no te va a fallar y a la que le puedes confiar tus mayores secretos.",
        translation_en: "Esta frase define el significado de amistad y resalta la importancia de la confianza plena en alguien. Sin duda, quien tiene un amigo tiene un tesoro y debemos valorar esta conexión con otras personas.",
    },
    {
        index: 17,
        latin: "💐 *Autor:* *Buddha*",
        arabic: "💐 *Frase:* _El dolor es inevitable pero el sufrimiento es opcional._",
        translation_id: "💐 *Opinión:* Todos podemos vivir experiencias que nos hagan sufrir y pasarlo mal, y esto tiene un proceso para superarlo pues es parte de la vida.",
        translation_en: "Pero nosotros tenemos la posibilidad de hacer cosas para no quedarnos estancados en el sufrimiento. Por tanto, es decisión nuestra superar las malas experiencias lo antes posible.",
    },
    {
        index: 18,
        latin: "💐 *Autor:* *David Abernathy*",
        arabic: "💐 *Frase:* _Se puede matar al soñador, pero no al sueño._",
        translation_id: "💐 *Opinión:* Una frase que nos explica que la carne es finita, pero no así las ideas.",
        translation_en: "Incluso lo intagible es finito.",
    },
    {
        index: 19,
        latin: "💐 *Autor:* *Benjamin Franklin*",
        arabic: "💐 *Frase:* _Quien tiene paciencia, obtendrá lo que desea._",
        translation_id: "💐 *Opinión:* Uno de los primeros presidentes de los Estados Unidos nos informa sobre la gran virtud que es la paciencia.",
        translation_en: "Dicha virtud que no todos tienen.",
    },
    {
        index: 20,
        latin: "💐 *Autor:* *Pitágoras*",
        arabic: "💐 *Frase:* _Educad a los niños, y no será necesario castigar a los hombres._",
        translation_id: "💐 *Opinión:* Pitágoras el griego sobre la gran trascendencia de la educación en una sociedad.",
        translation_en: "Hacer el mal a alguien en su plena etapa de cremiento no es bueno.",
    },
    {
        index: 21,
        latin: "💐 *Autor:* *Confucio*",
        arabic: "💐 *Frase:* _Aprender sin reflexionar es malgastar la energía._",
        translation_id: "💐 *Opinión:* El sabio pensador chino Confucio, sobre la necesidad de llevar a cabo un estilo de aprendizaje basado en la reflexión.",
        translation_en: "Saber no gastar el tiempo.",
    },
    {
        index: 22,
        latin: "💐 *Autor:* *Maquiavelo*",
        arabic: "💐 *Frase:* _Las personas ofenden antes a los que aman que a los que temen._",
        translation_id: "💐 *Opinión:* Las personas que son obstinadas pueden causarnos cierto miedo, es por eso que vamos con pies de plomo a la hora de tratar con ellas.",
        translation_en: "Tener cuidado con ese tipo de personas.",
    },
    {
        index: 23,
        latin: "💐 *Autor:* *Francis Bacon*",
        arabic: "💐 *Frase:* _La amistad duplica las alegrías y divide las angustias por la mitad._",
        translation_id: "💐 *Opinión:* Una verdad innegable; la vida es menos cruda cuando la pasamos cerca de personas que nos quieren de forma genuina.",
        translation_en: "La amistad puede ser buena dependiendo de las personas.",
    },
    {
        index: 24,
        latin: "💐 *Autor:* *Friedrich Nietzsche*",
        arabic: "💐 *Frase:* _Solamente aquel que construye el futuro tiene derecho a juzgar el pasado._",
        translation_id: "💐 *Opinión:* Nietzsche nos dejó muchas citas célebres, como por ejemplo esta, que nos indica la relevancia de tomar el control de nuestras vidas.",
        translation_en: "Recuerda tomar Agua. 👀",
    },
    {
        index: 25,
        latin: "💐 *Autor:* *Johann Kaspar Lavater*",
        arabic: "💐 *Frase:* _Si quieres ser sabio, aprende a interrogar razonablemente, a escuchar con atención, a responder serenamente y a callar cuando no tengas nada que decir._",
        translation_id: "💐 *Opinión:* Unos consejos prácticos para alcanzar altas cotas de inteligencia y sabiduría.",
        translation_en: "Consejos que salvan vidas.",
    },
    {
        index: 26,
        latin: "💐 *Autor:* *Jorge Luis Borges*",
        arabic: "💐 *Frase:* _He cometido el peor pecado que uno puede cometer. No he sido feliz._",
        translation_id: "💐 *Opinión:* Borges nos dejó esta reflexión, que demuestra que no estuvo suficientemente atento a gozar de la vida.",
        translation_en: "Vivela, tal vez sea la ultima.",
    },
    {
        index: 27,
        latin: "💐 *Autor:* *Platón*",
        arabic: "💐 *Frase:* _La libertad está en ser dueños de nuestra propia vida._",
        translation_id: "💐 *Opinión:* La libertad es uno de los conceptos más ampliamente estudiados por los filósofos.",
        translation_en: "Aquí, Platón nos explica cuál es la clave para ser libre.",
    },
    {
        index: 28,
        latin: "💐 *Autor:* *René Descartes*",
        arabic: "💐 *Frase:* _Daría todo lo que sé, por la mitad de lo que ignoro._",
        translation_id: "💐 *Opinión:* El francés René Descartes también era totalmente consciente de que, a pesar de ser uno de los más brillantes pensadores modernos, ignoraba mucho más de lo que conocía.",
        translation_en: "Ignorar las cosas, no es bueno.",
    },
    {
        index: 29,
        latin: "💐 *Autor:* *Baltasar Gracián*",
        arabic: "💐 *Frase:* _Saber y saberlo demostrar es valer dos veces._",
        translation_id: "💐 *Opinión:* Una de las diferencias entre el conocimiento superficial y el conocimiento profundo, según Baltasar Gracián.",
        translation_en: "Poner en práctica lo que sabes.",
    },
    {
        index: 30,
        latin: "💐 *Autor:* *Lao-tsé*",
        arabic: "💐 *Frase:* _Saber que no se sabe, eso es humildad. Pensar que uno sabe lo que no sabe, eso es enfermedad._",
        translation_id: "💐 *Opinión:* Lao-tsé ahonda en el asunto de la ignorancia y la percepción de sabiduría, en la línea de otros pensadores que pronunciaron frases similares.",
        translation_en: "No ser ignorante.",
    },
    {
        index: 31,
        latin: "💐 *Autor:* *Epicteto de Frigia*",
        arabic: "💐 *Frase:* _La persona sabia no debe abstenerse de participar en el gobierno del Estado, pues es un delito renunciar a ser útil a los necesitados y un cobardía ceder el paso a los indignos._",
        translation_id: "💐 *Opinión:* Una reflexión de corte político; los ciudadanos sabios deben intentar participar en la gestión de la polis, para aportar su granito de arena a una administración que debe ser justa con todos.",
        translation_en: "Recuerda tener tiempo para todo.",
    },
    {
        index: 32,
        latin: "💐 *Autor:* *Confucio*",
        arabic: "💐 *Frase:* _La vida es muy simple, pero insistimos en hacerla complicada._",
        translation_id: "💐 *Opinión:* El filósofo Confucio creía que la vida se rige por principios simples que debemos adoptar como normas para nuestro día a día.",
        translation_en: "Es tan simple...",
    },
    {
        index: 33,
        latin: "💐 *Autor:* *Abraham Lincoln*",
        arabic: "💐 *Frase:* _Al final, no son los años en nuestra vida lo que cuenta, sino la vida en nuestros años._",
        translation_id: "💐 *Opinión:* Lincoln, sobre el criterio de calidad que según él deberíamos aplicar a la hora de valorar nuestras vidas.",
        translation_en: "Todos omiten el hecho que cada vez se acercan la muerte con el pasar del tiempo, pero si vives plenamente habrá valido la pena",
    },
    {
        index: 34,
        latin: "💐 *Autor:* *Voltaire*",
        arabic: "💐 *Frase:* _Cada persona es una criatura del tiempo en el que vive._",
        translation_id: "💐 *Opinión:* Voltaire creía que no podemos considerarnos seres independizados del contexto histórico que nos toca vivir.",
        translation_en: "Nuestras ideas y nuestro modo de vida están siempre condicionados por la fecha de nuestro nacimiento.",
    },
    {
        index: 35,
        latin: "💐 *Autor:* *Aristóteles*",
        arabic: "💐 *Frase:* _Somos lo que hacemos repetidamente._",
        translation_id: "💐 *Opinión:* Aristóteles se distanció del idealismo de Platón; para él importaban más los hechos y el entorno, y esto queda claro en esta frase de la vida eminentemente filosófica.",
        translation_en: "Repetir nos hace mejor.",
    },
    {
        index: 36,
        latin: "💐 *Autor:* *Charlie Chaplin*",
        arabic: "💐 *Frase:* _La vida es una tragedia cuando se ve en primer plano, pero en plano general pasa a ser una comedia._",
        translation_id: "💐 *Opinión:* Chaplin, como director de cine, sabía que un mismo hecho, o incluso la vida de una persona, cambia dependiendo del modo en el que se presente.",
        translation_en: "Malos y buenos momentos.",
    },
    {
        index: 37,
        latin: "💐 *Autor:* *Albert Camus*",
        arabic: "💐 *Frase:* _El hombre es la única criatura que se niega a ser quien es._",
        translation_id: "💐 *Opinión:* Albert Camus, en una de sus frases filosóficas acerca de la lucha que el ser humano mantiene con la creación de un sentido para su existencia.",
        translation_en: "Aprende aceptar lo que eres.",
    },
    {
        index: 38,
        latin: "💐 *Autor:* *Cassandra Clare*",
        arabic: "💐 *Frase:* _Todo conocimiento resulta hiriente._",
        translation_id: "💐 *Opinión:* Una frase sabia referida al modo en el que cada nueva pieza de conocimiento trastoca los cimientos de lo que creíamos que sabíamos.",
        translation_en: "Siempre hay algo por aprender",
    },
    {
        index: 39,
        latin: "💐 *Autor:* *Pablo Picasso*",
        arabic: "💐 *Frase:* _Lleva mucho tiempo llegar a ser joven._",
        translation_id: "💐 *Opinión:* El reputado pintor invierte el orden temporal en el que se ubica la juventud para dar a entender que es, más que una fase biológica, algo aprendido.",
        translation_en: "Recuerda ser buena persona 😸",
    },
    {
        index: 40,
        latin: "💐 *Autor:* *Hannah Arendt*",
        arabic: "💐 *Frase:* _El tiempo es aquello que más queremos y también lo que peor utilizamos._",
        translation_id: "💐 *Opinión:* La filósofa Hannah Arendt, sobre el riesgo que conlleva la simple actividad de pensar.",
        translation_en: "Pensar nos hace mas autosuficientes.",
    },
    {
        index: 41,
        latin: "💐 *Autor:* *William Penn*",
        arabic: "💐 *Frase:* _No hay pensamientos peligrosos; pensar es, en sí mismo, algo peligroso._",
        translation_id: "💐 *Opinión:* Una paradoja planteada por el filósofo inglés William Penn. Para ser conscientes de que la vida está para saberla aprovechar al máximo.",
        translation_en: "Si fuera posible cambiarlo, es probable el resultado de la paradoja del abuelo.",
    },
    {
        index: 42,
        latin: "💐 *Autor:* *David Ben-Gurión*",
        arabic: "💐 *Frase:* _Alguien que no cree en los milagros no es realista._",
        translation_id: "💐 *Opinión:* Acerca de las anomalías y hechos inexplicables contenidos en la realidad.",
        translation_en: "Si nunca has estado enfrente de una anomalía, tal vez pienses que no existe.",
    },
    {
        index: 43,
        latin: "💐 *Autor:* *Francis Bacon*",
        arabic: "💐 *Frase:* _La esperanza es un buen desayuno, pero una mala cena._",
        translation_id: "💐 *Opinión:* La esperanza como algo que tiene doble filo. ",
        translation_en: "Resulta positiva cuando todo un mundo de posibilidades se abre ante nosotros, pero no tanto cuando es el último recurso.",
    },
    {
        index: 44,
        latin: "💐 *Autor:* *Allan Bloom*",
        arabic: "💐 *Frase:* _La educación es el movimiento de la oscuridad a la luz._",
        translation_id: "💐 *Opinión:* Una imagen potente para explica lo que es la educación.",
        translation_en: "Imagen que dependiendo de como lo imaginas puede tener la verdad sobre ti",
    },
    {
        index: 45,
        latin: "💐 *Autor:* *Erich Fromm*",
        arabic: "💐 *Frase:* _La creatividad requiere que la valentía se desprenda de las certezas._",
        translation_id: "💐 *Opinión:* El padre del psicoanálisis humanista, sobre la relación entre la valentía y la incertidumbre.",
        translation_en: "Ser valiente te hace creativo/a",
    },
    {
        index: 46,
        latin: "💐 *Autor:* *Edmund Burke*",
        arabic: "💐 *Frase:* _Aquellos que no conocen la historia están condenados a repetirla._",
        translation_id: "💐 *Opinión:* El filósofo conservador Edmund Burke, sobre la necesidad de conocer el pasado.",
        translation_en: "Conoce el Pasado, te ahorra tiempo a un Futuro.",
    },
    {
        index: 47,
        latin: "💐 *Autor:* *Cicerón*",
        arabic: "💐 *Frase:* _Nada es tan increíble como para que la oratoria no lo pueda transformar en aceptable._",
        translation_id: "💐 *Opinión:* Cicerón habla sobre el poder de los discursos bien diseñados.",
        translation_en: "Un discurso puede convencer a muchos.",
    },
    {
        index: 48,
        latin: "💐 *Autor:* *Dante*",
        arabic: "💐 *Frase:* _De una pequeña chispa puede prender una llama._",
        translation_id: "💐 *Opinión:* Una frase sabia en la que se entrevé, mediante una imagen poética.",
        translation_en: "Modos insospechados en los que pueden aparecer fenómenos muy importantes y significativos.",
    },
    {
        index: 49,
        latin: "💐 *Autor:* *Dante*",
        arabic: "💐 *Frase:* _El liderazgo no depende de estar en lo cierto._",
        translation_id: "💐 *Opinión:* Uno de los pensadores sobre la educación más importantes habla aquí sobre el modo en el que tenemos que interpretar la legitimidad del liderazgo.",
        translation_en: "Recuerda, si dices saberlo todo, eres un ignorante.",
    },
    {
        index: 50,
        latin: "💐 *Autor:* *B. F. Skinner*",
        arabic: "💐 *Frase:* _El entorno da forma a las acciones del individuo._",
        translation_id: "💐 *Opinión:* El referente más importante de la psicología conductista habla sobre lo relativo de esa línea que separa individuo y entorno.",
        translation_en: "El entorno determina tus acciones.",
    },
    {
        index: 51,
        latin: "💐 *Autor:* *Stanislaw Jerzy Lec*",
        arabic: "💐 *Frase:* _La juventud es un reglo de la naturaleza, pero la edad es una obra de arte._",
        translation_id: "💐 *Opinión:* Un modo optimista de valorar la edad y el paso hacia la vejez.",
        translation_en: "La edad no determina tu forma de ver el mundo.",
    },
    {
        index: 52,
        latin: "💐 *Autor:* *Stanislaw Jerzy Lec*",
        arabic: "💐 *Frase:* _Nadie puede herirme sin mi permiso._",
        translation_id: "💐 *Opinión:* El influyente líder pacifista se refiere en esta frase sabia al poder de la propia voluntad.",
        translation_en: "Tener el agrado hacia lo que haces permitira que tu voluntad no se obstruya.",
    },
    {
        index: 53,
        latin: "💐 *Autor:* *David Carradine*",
        arabic: "💐 *Frase:* _Si no puedes ser poeta, sé el poema._",
        translation_id: "💐 *Opinión:* Una perspectiva diferente para ver el modo en el que nuestra vida puede tener carácter artístico.",
        translation_en: "Aprender a tener varias habilidades.",
    },
    {
        index: 54,
        latin: "💐 *Autor:* *Eurípides*",
        arabic: "💐 *Frase:* _Nada tiene más fuerza que la extrema necesidad._",
        translation_id: "💐 *Opinión:* El poeta griego Eurípides habla sobre cómo, en última instancia , el poder de nuestros actos nace cuando nuestra libertad y situación para tomar decisiones se ven reducidas.",
        translation_en: "La necesidad puede ser un peligro.",
    },
    {
        index: 55,
        latin: "💐 *Autor:* *San Agustín*",
        arabic: "💐 *Frase:* _La soberbia no es grandeza sino hinchazón; y lo que está hinchado parece grande pero no está sano._",
        translation_id: "💐 *Opinión:* Uno de los problemas de la soberbia es que, tras la apariencia, esconde a alguien herido e inseguro.",
        translation_en: "La inseguridad hace que te veas menos.",
    },
    {
        index: 56,
        latin: "💐 *Autor:* *William Shakespeare*",
        arabic: "💐 *Frase:* _Es mejor ser rey de tu silencio que esclavo de tus palabras._",
        translation_id: "💐 *Opinión:* Nunca digas cosas de las que te puedas arrepentir en el futuro.",
        translation_en: "Cuando sucede eso, estas pensando de manera irracional.",
    },
    {
        index: 57,
        latin: "💐 *Autor:* *William Shakespeare*",
        arabic: "💐 *Frase:* _La belleza es poder; una sonrisa es su espada._",
        translation_id: "💐 *Opinión:* Una reflexión sobre la belleza y sus principales atributos.",
        translation_en: "Atributos que pueden ser arma de doble filo.",
    },
    {
        index: 58,
        latin: "💐 *Autor:* *Ogden Nash*",
        arabic: "💐 *Frase:* _La edad adulta es cuando te has encontrado con tanta gente que cada nueva persona te recuerda a otra._",
        translation_id: "💐 *Opinión:* Entonces, nada te sorprende.",
        translation_en: "La sabiduría de la edad adulta comporta unos ciertos problemas, como este que retrata Ogden Nash.",
    },
    {
        index: 59,
        latin: "💐 *Autor:* *Severo Ochoa*",
        arabic: "💐 *Frase:* _En principio, la investigación necesita más cabezas que medios._",
        translation_id: "💐 *Opinión:* Una frase de la vida y la ciencia que nos muestra la importancia del talento humano.",
        translation_en: "Talento humano, todos tienen almenos uno.",
    },
    {
        index: 60,
        latin: "💐 *Autor:* *Maquiavelo*",
        arabic: "💐 *Frase:* _El que es elegido príncipe con el favor popular debe conservar al pueblo como amigo._",
        translation_id: "💐 *Opinión:* Una reflexión de corte político según el mítico historiador italiano.",
        translation_en: "Una frase un tanto medieval.",
    },
    {
        index: 61,
        latin: "💐 *Autor:* *Camilo José Cela*",
        arabic: "💐 *Frase:* _La Historia nos enseña dos cosas: que jamás los poderosos coincidieron con los mejores, y que jamás la política fue tejida por los políticos._",
        translation_id: "💐 *Opinión:* Sobre la política y la hegemonía, del gran escritor Camilo José Cela.",
        translation_en: "Poderosos que tal vez esten solos.",
    },
    {
        index: 62,
        latin: "💐 *Autor:* *José Ortega y Gasset*",
        arabic: "💐 *Frase:* _Con la moral corregimos los errores de nuestros instintos, y con el amor los errores de nuestra moral._",
        translation_id: "💐 *Opinión:* El ensayista español realiza una disquisición que cada uno debe interpretar.",
        translation_en: "Aprender a equivocarse. Irónico.",
    },
    {
        index: 63,
        latin: "💐 *Autor:* *Novalis*",
        arabic: "💐 *Frase:* _Cuando veas un gigante, examina antes la posición del sol; no vaya a ser la sombra de un pigmeo._",
        translation_id: "💐 *Opinión:* El engañarse ante su entorno.",
        translation_en: "Nuestra percepción puede engañarnos, por tanto tómate tu tiempo para reflexionar sobre las pequeñas cosas de la vida.",
    },
    {
        index: 64,
        latin: "💐 *Autor:* *Platón*",
        arabic: "💐 *Frase:* _La pobreza no viene por la disminución de las riquezas, sino por la multiplicación de los deseos._",
        translation_id: "💐 *Opinión:* Una reflexión del filósofo griego en que resalta el vicio de la avaricia.",
        translation_en: "Avaricia abunda en las personas sin caminos.",
    },
    {
        index: 65,
        latin: "💐 *Autor:* *Ovidio*",
        arabic: "💐 *Frase:* _No os entreguéis por demasiado a la ira; una ira prolongada engendra odio._",
        translation_id: "💐 *Opinión:* La rabia puede traernos consecuencias nefastas en nuestra vida.",
        translation_en: "No darle importancia al odio.",
    },
    {
        index: 66,
        latin: "💐 *Autor:* *Kant*",
        arabic: "💐 *Frase:* _La educación es el desarrollo sobre la persona de toda la perfección de que su naturaleza es capaz._",
        translation_id: "💐 *Opinión:* Para concluir la selección de frases, esta reflexión del filósofo alemán para evidenciar la importancia de la educación.",
        translation_en: "La educación lo es todo.",
    },
    {
        index: 67,
        latin: "💐 *Autor:* *Arturo Pérez-Reverte*",
        arabic: "💐 *Frase:* _El problema de las palabras es que, una vez echadas, no pueden volverse solas a su dueño. De modo que a veces te las vuelven en la punta de un acero._",
        translation_id: "💐 *Opinión:* El literato español, sobre la crueldad de lo dicho.",
        translation_en: "Recuerda decir bien las cosas, sin arrepentimientos.",
    },
    {
        index: 68,
        latin: "💐 *Autor:* *Winston Churchill*",
        arabic: "💐 *Frase:* _El esfuerzo constante – no la fuerza o la inteligencia – es la clave para liberar nuestro potencial._",
        translation_id: "💐 *Opinión:* Mítica reflexión sobre la constancia y la perseverancia.",
        translation_en: "Todo esfuerzo tiene su recompensa.",
    },
    {
        index: 69,
        latin: "💐 *Autor:* *Ernesto Sábato*",
        arabic: "💐 *Frase:* _Ser original es en cierto modo estar poniendo de manifiesto la mediocridad de los demás._",
        translation_id: "💐 *Opinión:* Una de esas frases sabias no aptas para mentes cerradas.",
        translation_en: "Hay que saber ser Original en base a ideas que existen con un estilo propio.",
    },
    {
        index: 70,
        latin: "💐 *Autor:* *Mark Twain*",
        arabic: "💐 *Frase:* _No hay nada tan grotesco o increíble que el ser humano medio no pueda creer._",
        translation_id: "💐 *Opinión:* La imaginación no tiene límites, para bien o para mal.",
        translation_en: "Recuerda imaginar paera bien.",
    },
    {
        index: 71,
        latin: "💐 *Autor:* *Napoleón*",
        arabic: "💐 *Frase:* _Nunca interrumpas a tu enemigo cuanto está cometiendo una equivocación._",
        translation_id: "💐 *Opinión:* Un consejo táctico de este famoso militar.",
        translation_en: "Recuerda siempre tener ventajas.",
    },
    {
        index: 72,
        latin: "💐 *Autor:* *Lao-Tsé*",
        arabic: "💐 *Frase:* _Conocer a los demás es sabiduría; conocerse a uno mismo es iluminación._",
        translation_id: "💐 *Opinión:* El auto-conocimiento como aspecto fundamental de la vida.",
        translation_en: "Hay que tener iniciativa para aprender en el camino por cuenta propia.",
    },
    {
        index: 73,
        latin: "💐 *Autor:* *Charles Bukowski*",
        arabic: "💐 *Frase:* _Estamos aquí para vivir nuestras vidas tan bien que la Muerte tiemble al arrebatárnoslas._",
        translation_id: "💐 *Opinión:* Una credencia del vitalismo.",
        translation_en: "Vive como si fuera el último día.",
    },
    {
        index: 74,
        latin: "💐 *Autor:* *B.F. Skinner*",
        arabic: "💐 *Frase:* _No deberíamos instruir en la lectura de libros, sino enseñar a amar los libros._",
        translation_id: "💐 *Opinión:* Un aprendizaje de tipo emocional.",
        translation_en: "Un mundo de letras...",
    },
    {
        index: 75,
        latin: "💐 *Autor:* *Martin Luther King*",
        arabic: "💐 *Frase:* _Tu verdad aumentará en la medida que sepas escuchar la verdad de los otros._",
        translation_id: "💐 *Opinión:* La sabiduría no está compuesta de descubrimientos realizados individualmente.",
        translation_en: "Sino que incluye lo que aprendemos de los demás.",
    },
    {
        index: 76,
        latin: "💐 *Autor:* *Mario Benedetti*",
        arabic: "💐 *Frase:* _No te rindas, porque cada día es un comienzo nuevo, porque esta es la hora y el mejor momento._",
        translation_id: "💐 *Opinión:* Una manera de ver el ahora que además nos sirve como fuente de motivación.",
        translation_en: "La paz se puede si todos están de acuerdo.",
    },
    {
        index: 77,
        latin: "💐 *Autor:* *Erasmo de Rotterdam*",
        arabic: "💐 *Frase:* _La paz más desventajosa es mejor que la guerra más justa._",
        translation_id: "💐 *Opinión:* Una apreciación moral acerca del valor de la paz.",
        translation_en: "En la guerra nadie gana, solo hay dolor.",
    },
    {
        index: 78,
        latin: "💐 *Autor:* *Baruch Spinoza*",
        arabic: "💐 *Frase:* _Si no quieres repetir el pasado, estúdialo._",
        translation_id: "💐 *Opinión:* La memoria nos permite aprender de nuestros errores, y eso es algo que hay que aprovechar.",
        translation_en: "Es la mejor manera de no volver a caer.",
    },
    {
        index: 79,
        latin: "💐 *Autor:* *Anselmo de Canterbury*",
        arabic: "💐 *Frase:* _Los desastres nos enseñan humildad._",
        translation_id: "💐 *Opinión:* Incluso las crisis tienen algo bueno, pues nos recuerdan nuestro escaso poder frente al mundo.",
        translation_en: "El ser humano no puede con todo.",
    },
    {
        index: 80,
        latin: "💐 *Autor:* *Nelson Mandela*",
        arabic: "💐 *Frase:* _No hay nada como volver a un lugar que permanece sin cambiar para encontrar las formas en las que tú mismo has cambiado._",
        translation_id: "💐 *Opinión:* La interacción con el entorno nos permite conocernos mejor.",
        translation_en: "Recordar que todo sigue igual... Es un buen sentimiento.",
    },
    {
        index: 81,
        latin: "💐 *Autor:* *Epícuro*",
        arabic: "💐 *Frase:* _Cuanto más grande es la dificultad, más gloria hay en superarla._",
        translation_id: "💐 *Opinión:* El filósofo griego, fundador epicureísmo, nos deja esta gran frase motivadora para la historia.",
        translation_en: "Saberse superar....",
    },
    {
        index: 82,
        latin: "💐 *Autor:* *Friedrich Hegel*",
        arabic: "💐 *Frase:* _Ser independiente de la opinión pública es la primera condición formal para lograr algo grande._",
        translation_id: "💐 *Opinión:* Pensar nos hace ver las cosas de una manera alterna.",
        translation_en: "Una frase que habla del pensamiento propio.",
    },
    {
        index: 83,
        latin: "💐 *Autor:* *Leibniz*",
        arabic: "💐 *Frase:* _Vivimos en el mejor de los posibles mundos._",
        translation_id: "💐 *Opinión:* Al menos éste es el único que conocemos.",
        translation_en: "Con sus cosas buenas y sus cosas malas.",
    },
    {
        index: 84,
        latin: "💐 *Autor:* *Benjamin Franklin*",
        arabic: "💐 *Frase:* _El que es bueno para poner excusas rara vez es bueno para cualquier otra cosa._",
        translation_id: "💐 *Opinión:* Los cobardes ponen excusas en vez de afrontar la realidad.",
        translation_en: "Solo sabe evadir, y no afrontar.",
    },
    {
        index: 85,
        latin: "💐 *Autor:* *Noam Chomsky*",
        arabic: "💐 *Frase:* _Si no creemos en la libertad de expresión de las personas que despreciamos, no creemos en ella en absoluto._",
        translation_id: "💐 *Opinión:* Una frase que nos recuerda la importancia de la libertad de expresión.",
        translation_en: "La libertad es buena cuando somos libre de manera educada.",
    },
    {
        index: 86,
        latin: "💐 *Autor:* *Tales*",
        arabic: "💐 *Frase:* _La cosa más difícil en la vida es conocerte a ti mismo._",
        translation_id: "💐 *Opinión:* El autoconocimiento es clave para tener una vida emocional sana.",
        translation_en: "Siempre es bueno no dejar de aprender.",
    },
    {
        index: 87,
        latin: "💐 *Autor:* *Epíteto*",
        arabic: "💐 *Frase:* _No es lo que te ocurre, sino cómo reaccionas lo que importa._",
        translation_id: "💐 *Opinión:* Sobre la importancia de evaluar de forma positiva los hechos.",
        translation_en: "Hasta lo malo puede ser bueno.",
    },
    {
        index: 88,
        latin: "💐 *Autor:* *George Savile*",
        arabic: "💐 *Frase:* _La persona que es una maestra en la paciencia puede con todo lo demás._",
        translation_id: "💐 *Opinión:* Una frase del personaje célebre George Savile que hablar del poder de la paciencia.",
        translation_en: "Si te consideras una persona paciente, vales mucho como persona.",
    },
    {
        index: 89,
        latin: "💐 *Autor:* *Mark Twain*",
        arabic: "💐 *Frase:* _No hay una visión más triste que la de un joven pesimista._",
        translation_id: "💐 *Opinión:* Mark Twain habla sobre el valor asociado a la juventud y el error de desperdiciar esta etapa de la vida.",
        translation_en: "Es muy joven el mundo como para estar triste.",
    },
    {
        index: 90,
        latin: "💐 *Autor:* *Umberto Eco*",
        arabic: "💐 *Frase:* _Nada es más nocivo para la creatividad que el furor de la inspiración._",
        translation_id: "💐 *Opinión:* Una gran frase del siempre recordado, Umberto Eco.",
        translation_en: "Todos tenemos una idea de la vida.",
    },
    {
        index: 91,
        latin: "💐 *Autor:* *Emerson*",
        arabic: "💐 *Frase:* _El éxito consiste en obtener lo que se desea. La felicidad, en disfrutar lo que se obtiene._",
        translation_id: "💐 *Opinión:* Una frase que deberíamos tener siempre en nuestra cabeza.",
        translation_en: "Disfrutar del esfuerzo...",
    },
    {
        index: 92,
        latin: "💐 *Autor:* *Henry David Thoreau*",
        arabic: "💐 *Frase:* _Casi todas las personas viven la vida en una silenciosa desesperación._",
        translation_id: "💐 *Opinión:* Una frase que pretende explicar la complejidad de la vida y los malos momentos que uno puede experimentar.",
        translation_en: "Experimentar la vida y ver como nos sorprende.",
    },
    {
        index: 93,
        latin: "💐 *Autor:* *D. Pire*",
        arabic: "💐 *Frase:* _Andaríamos mejor si no fuera porque hemos construido demasiados muros y no suficientes puentes._",
        translation_id: "💐 *Opinión:* Una frase sobre lo peor del ser humano. Los muros nunca han sido buenos.",
        translation_en: "Divider el mundo solo hace ser menos fuerte todo.",
    },
    {
        index: 94,
        latin: "💐 *Autor:* *Jairo Fowbier Pabón*",
        arabic: "💐 *Frase:* _La experiencia no es cuanto se vive sino todo el bien que se aprende._",
        translation_id: "💐 *Opinión:* La experiencia nos sirve para aprender.",
        translation_en: "Aprender es saber asumir que no lo sabes todo.",
    },
    {
        index: 95,
        latin: "💐 *Autor:* *Chamfort*",
        arabic: "💐 *Frase:* _La falsa modestia es la más decente de todas las mentiras._",
        translation_id: "💐 *Opinión:* Hace referencia a la falsa modestia. Pues, dentro de las mentiras, es la menos mala.",
        translation_en: "Hay que ser directo(a) en todo.",
    },
    {
        index: 96,
        latin: "💐 *Autor:* *C.G. Jung*",
        arabic: "💐 *Frase:* _Tú eres aquello que haces, no aquello que dices que harás._",
        translation_id: "💐 *Opinión:* Tus acciones determinan aquello que eres, no tus palabras.",
        translation_en: "Si vas a decirlo demuestra que lo puedes cumplir.",
    },
    {
        index: 97,
        latin: "💐 *Charles Dickens*",
        arabic: "💐 *Frase:* _El corazón humano es un instrumento de muchas cuerdas; el perfecto conocedor de personas, las sabe hacer vibrar todas, como un buen músico._",
        translation_id: "💐 *Opinión:* La persona que se conoce es una persona poderosa.",
        translation_en: "Siempre hay algo nuevo por conocer.",
    },
    {
        index: 98,
        latin: "💐 *Solomon Asch*",
        arabic: "💐 *Frase:* _La mayoría de actos sociales deben ser entendidos en su contexto, ya que pierden significado si son aislados._",
        translation_id: "💐 *Opinión:* Las personas somos seres biopsicosociales.",
        translation_en: "Es decir, el contexto es importante en influye en cómo actuamos.",
    },
    {
        index: 99,
        latin: "💐 *Erich Fromm*",
        arabic: "💐 *Frase:* _Si una persona ama solo a una persona y es indiferente ante todos los demás, su amor no es amor, sino apego simbiótico o egoísmo ampliada._",
        translation_id: "💐 *Opinión:* Cuando estamos enamorados de alguien, daríamos la vida por esa persona.",
        translation_en: "Podemos engañarnos y creer que somos buenas personas, pero hasta los más egoístas pueden perder la cabeza por alguien y parecer personas entregadas.",
    }
]
